language: ruby
sudo: required
dist: trusty
script: bundle exec rake test
env:
  global:
    - PUBLISHER_LOGIN=spotify
    - secure: "KGbNZWC3AtY658oj/+dUwcTOQ1mbwJc14vJpQ5PXpwfDU13h11uIT5JoU4NLEA3kaevGimgD803b8jUG1EgJT1bipWRd3xeYn6Ak/yW75UlwbfPDPTrmlCrnSFNTCnkMGs56R4hOY1ZsfSmgBVHBg20Gcg8sXCb32ok0f5Gfpgg="
matrix:
  fast_finish: true
deploy:
  provider: puppetforge
  username: spotify
  password:
    secure: "If1DswgaU2PiIJ32HjLEMTLYmPinlLtxdMXWUznXM/ReXkK7d1L6T/OxuEAwX3eGN/YPxJjB/t53KZ2aleb6QddNW4voKe0PidVQBdVmwmm7WRJOkIJhRw0gEeZWwQnDA1yK+7rUFTL4nmooY2C8neEIogsC3EbGHu4/zmR5+1w="
  on:
    tags: true
