HOSTS:
  debian-7:
    roles:
      - default
    platform: debian-7-amd64
    image: debian:7
    docker_image_commands:
      - 'apt-get install -y wget net-tools'
    hypervisor: docker
CONFIG:
  log_level: verbose
  type: aio
